import type { Metadata } from 'next';
import Link from 'next/link';
import LegalPage, { Section } from '@/components/legal/LegalPage';
import { SUPPORT_EMAIL } from '@/lib/legal';

export const metadata: Metadata = {
  title: 'Terms of Service — Politicon',
  description: 'The terms for using Politicon.',
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro="These terms govern your use of Politicon. By creating an account you agree to them. Please read them together with our Privacy Policy and Disclaimer."
    >
      <Section title="What Politicon is">
        <p>Politicon is an educational tool. It uses AI to explain government policies and to estimate how they might affect a household like yours, based on the ranges you provide. Its estimates are informational only. Politicon is not a financial, tax, legal or investment advisor, and it is not affiliated with any government agency, party or campaign.</p>
      </Section>

      <Section title="Eligibility and your account">
        <ul className="list-disc pl-5 space-y-2">
          <li>You must be at least 18 years old.</li>
          <li>Provide accurate information and keep your password secure. You&apos;re responsible for activity under your account.</li>
          <li>One person per account. Don&apos;t share accounts or create them in bulk.</li>
        </ul>
      </Section>

      <Section title="Acceptable use">
        <p>Don&apos;t misuse the service. In particular, don&apos;t:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>try to get around rate limits, usage limits or security controls;</li>
          <li>use automated tools to scrape the service or generate requests at scale;</li>
          <li>try to make the AI produce harmful, deceptive or unlawful content, or use it to impersonate others;</li>
          <li>use Politicon to target, harass or mislead voters.</li>
        </ul>
        <p>We may limit, suspend or close accounts that break these rules.</p>
      </Section>

      <Section title="AI-generated content">
        <p>Analyses, feeds and chat replies are generated by AI and can be wrong, incomplete or out of date. They depend on the ranges you provide and on assumptions shown alongside them. Always check important facts against official sources and consider talking to a qualified professional before acting. See the <Link className="text-primary hover:underline" href="/disclaimer">Disclaimer</Link>.</p>
      </Section>

      <Section title="Your content">
        <p>You own what you put into Politicon. You give us permission to store and process it only to provide the service to you, as described in the <Link className="text-primary hover:underline" href="/privacy">Privacy Policy</Link>. You can export or delete it at any time.</p>
      </Section>

      <Section title="Availability and changes">
        <p>We may change, pause or discontinue features, and AI features have daily usage limits. We&apos;ll update these terms when the service changes; if a change is material we&apos;ll tell you in the app before it takes effect.</p>
      </Section>

      <Section title="Liability">
        <p>Politicon is provided &ldquo;as is&rdquo;, without warranties of any kind. To the fullest extent the law allows, we are not liable for decisions you make based on its estimates, or for indirect or consequential losses.</p>
      </Section>

      <Section title="Ending your account">
        <p>You can delete your account at any time from Settings. We may close accounts that break these terms.</p>
      </Section>

      <Section title="Contact">
        <p><a className="text-primary hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a></p>
      </Section>
    </LegalPage>
  );
}
